### ISSUE TITLE
Work out a policy for handling transfer of abandoned repositories

### ISSUE THREAD

**Issue by jchodera** [livecomsjournal/journal_information#22]
A policy is needed to handle this.

**Comment by davidlmobley** [comment]
Yes, absolutely. We should have an explicit policy that all submitters agree to so that if authors die or abandon an article that the community wants to continue, they have **already given consent for us to come up with a way to continue it**.

**Comment by davidlmobley** [comment]
To a large extent, we realized, this is handled by use of the CC-BY 4.0 license since it grants the right to remix, extend, create derivative works, etc. 

At the same time, there are still issues of "academic courtesy" or authorship that the license does not address. Suppose I co-author an article with John, but then we both die or one dies and the other leaves the field or becomes unresponsive (retires?), and someone else wants to pick up an continue our article and add themselves as an author. CC-BY 4.0 might give them a right to do this, but should they do so and be able to and publish a new version? Or should the journal worry about, "Well, but Chodera and Mobley didn't consent to this!" So I think we want a policy that explicitly allows for "chain of command" or "succession" issues in this scenario to resolve these sorts of courtesy/authorship issues.

**Comment by mrshirts** [comment]
Started a document to host this as https://github.com/livecomsjournal/journal_information/pull/25

**Comment by mrshirts** [comment]
I think this  was properly dealt with by https://github.com/livecomsjournal/livecomsjournal.github.io/issues/22
