### ISSUE TITLE
Break up "for authors"

### ISSUE THREAD

**Issue by davidlmobley** [livecomsjournal/journal_information#6]
Reading through "for authors", I am wondering what we want this to provide?
a) Instructions for authors?
b) Information for authors?
c) Both? 

Right now it seems like a combination of all of the above, plus notes to ourselves. I THINK we should be going for "information for authors" with links to additional instructions they might need, and break off notes about how we do things to elsewhere.

I think we should break off the following as separate documents:

- Document preparation instructions: We can just have a one or two sentence summary of what needs to happen with a link to a detailed set of instructions that can be posted in the Editorial category
- It will be important for the document preparation instructions to note that accessibility to students is also important; this is the only part of the "review process" thing which will be especially important for authors to be aware of. 
- Review process: Authors don't have to know how it works; instead we should have submission instructions, I think. These can be more brief. We can have a separate document describing the review process and how versions are reviewed.
- Getting credit for contributions/addition of authors: This is important, but it'll get overlooked here. We want it a separate document so it can receive careful treatment and be linked to from a variety of places, including from  the versioning section of the revisions discussion.
- Policy on prior publication perhaps should also be moved?

One issue to be aware of with the website is that the text is fairly large, so relatively small amounts of content there can seem like a ton of text to read. So I'd try to keep it very concise. **I think the essentials to keep here are**:
- Quick intro as at present
- Before submission: Presubmission letter; use our LaTeX template and GitHub (link to document preparation instructions); note about accessibility to students
- Brief summary of submission instructions; link out to info on review process and info on how versions are reviewed
- Quick summary of goal of community contributions; link out to info on what warrants authorship
- Link to additional policies: Prior publication, licensing, ...

**Comment by mrshirts** [comment]
> Right now it seems like a combination of all of the above, plus notes to ourselves

So, right now it's all in one file because that's what the website gives us.   In terms of what we WANT:

I think what you lay out is pretty good.  I think we can shuffle things around, but it will be pretty easy once all of information is out. 

Here's my suggestion.  We start writing out these different documents in markdown in the journal_information repository.  We can then decide if we want to turn them into articles (like in LaTex, but easy, since just text), or put them some where else, like a Github pages.

David, how do you want to divide up the work on the documents?

**Comment by davidlmobley** [comment]
@mrshirts - I'm going to start with working on "Why LiveCoMS" and will see how far I get; I don't have that much time this weekend, so it's unclear. Why don't you start where you want, and I'll start with that, and then we can meet in the middle? 

(In other words, maybe you can post a list of things you'll work on in order, and when I start working on these I'll start at the bottom and work my way up.)

**Comment by mrshirts** [comment]
1) I will break up the "for authors" sections into roughly what you describe above. I will put the separate sections as .md files in editorial_material for now.   Should be done today (11/19). 

2) Once that text is in, I will experiment with two ways of posting it; as webpages on a github pages, and as pdf articles on Livecoms. Probably just start with one, since I will probably have to move the article to latex.

**Comment by davidlmobley** [comment]
A single article with well-delineated sections may be all that's needed; as I noted above one issue we're fighting with for material on the actual website is that the text is quite big so it looks like we have tons of random material on there even if we don't. If you format as a PDF, well organized into topical sections with clear headers, it will probably look like a nice short amount of material that's easy to read. 

Though, it still may ultimately make sense to split things up into at least a couple varieties of documents, as we're dealing with pretty disparate types of information here, including instructions and policies, info about how things work, etc.

**Comment by mrshirts** [comment]
I'm thinking fewer articles, organized into sections might be better.  Let me think about how to organize.

**Comment by mrshirts** [comment]
OK, I've rewritten the information as a shorter for_authors.md page, which I have copied over to the main web site.  It now links out to https://livecomsjournal.github.io for the expanded information, but this could be turned into an article on the journal as well.  I figured since this was the OTHER way to display the information (other than an article), it might be easier to start with displaying it this way, and we can try turning it into an article after.

This is PR https://github.com/livecomsjournal/journal_information/pull/10

**Comment by mrshirts** [comment]
Note - one the Markdown formatter on the scholastica web page leaves in page breaks.  So if we page break the .md files in github, then they look weird.  I could erase them when we copy the files over -- not a big deal if it happens somewhat infrequently.

**Comment by davidlmobley** [comment]
I think this all looks rather good to me now (at least as of my PR #9 which resolves some remaining issues), so I'm marking this as closed for now. Re-open if you disagree.
